/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface IRandomProviderInterface extends utils.Interface {
  functions: {
    "getCurrentRandom()": FunctionFragment;
    "getCurrentRandomWithQuality()": FunctionFragment;
    "getCurrentRandomWithQualityAndTimestamp()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getCurrentRandom"
      | "getCurrentRandomWithQuality"
      | "getCurrentRandomWithQualityAndTimestamp"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCurrentRandom",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRandomWithQuality",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRandomWithQualityAndTimestamp",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getCurrentRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRandomWithQuality",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRandomWithQualityAndTimestamp",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRandomProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRandomProviderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getCurrentRandom(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _randomNumber: BigNumber }>;

    getCurrentRandomWithQuality(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean] & {
        _randomNumber: BigNumber;
        _isSecureRandom: boolean;
      }
    >;

    getCurrentRandomWithQualityAndTimestamp(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber] & {
        _randomNumber: BigNumber;
        _isSecureRandom: boolean;
        _randomTimestamp: BigNumber;
      }
    >;
  };

  getCurrentRandom(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentRandomWithQuality(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean] & {
      _randomNumber: BigNumber;
      _isSecureRandom: boolean;
    }
  >;

  getCurrentRandomWithQualityAndTimestamp(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean, BigNumber] & {
      _randomNumber: BigNumber;
      _isSecureRandom: boolean;
      _randomTimestamp: BigNumber;
    }
  >;

  callStatic: {
    getCurrentRandom(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRandomWithQuality(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean] & {
        _randomNumber: BigNumber;
        _isSecureRandom: boolean;
      }
    >;

    getCurrentRandomWithQualityAndTimestamp(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber] & {
        _randomNumber: BigNumber;
        _isSecureRandom: boolean;
        _randomTimestamp: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    getCurrentRandom(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRandomWithQuality(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRandomWithQualityAndTimestamp(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCurrentRandom(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentRandomWithQuality(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentRandomWithQualityAndTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
