/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace TestFtsoV2Interface {
  export type FeedDataStruct = {
    votingRoundId: PromiseOrValue<BigNumberish>;
    id: PromiseOrValue<BytesLike>;
    value: PromiseOrValue<BigNumberish>;
    turnoutBIPS: PromiseOrValue<BigNumberish>;
    decimals: PromiseOrValue<BigNumberish>;
  };

  export type FeedDataStructOutput = [
    number,
    string,
    number,
    number,
    number
  ] & {
    votingRoundId: number;
    id: string;
    value: number;
    turnoutBIPS: number;
    decimals: number;
  };

  export type FeedDataWithProofStruct = {
    proof: PromiseOrValue<BytesLike>[];
    body: TestFtsoV2Interface.FeedDataStruct;
  };

  export type FeedDataWithProofStructOutput = [
    string[],
    TestFtsoV2Interface.FeedDataStructOutput
  ] & { proof: string[]; body: TestFtsoV2Interface.FeedDataStructOutput };
}

export interface TestFtsoV2InterfaceInterface extends utils.Interface {
  functions: {
    "getFeedById(bytes21)": FunctionFragment;
    "getFeedByIdInWei(bytes21)": FunctionFragment;
    "getFeedByIndex(uint256)": FunctionFragment;
    "getFeedByIndexInWei(uint256)": FunctionFragment;
    "getFeedId(uint256)": FunctionFragment;
    "getFeedIndex(bytes21)": FunctionFragment;
    "getFeedsById(bytes21[])": FunctionFragment;
    "getFeedsByIdInWei(bytes21[])": FunctionFragment;
    "getFeedsByIndex(uint256[])": FunctionFragment;
    "getFeedsByIndexInWei(uint256[])": FunctionFragment;
    "verifyFeedData((bytes32[],(uint32,bytes21,int32,uint16,int8)))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getFeedById"
      | "getFeedByIdInWei"
      | "getFeedByIndex"
      | "getFeedByIndexInWei"
      | "getFeedId"
      | "getFeedIndex"
      | "getFeedsById"
      | "getFeedsByIdInWei"
      | "getFeedsByIndex"
      | "getFeedsByIndexInWei"
      | "verifyFeedData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFeedById",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedByIdInWei",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedByIndex",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedByIndexInWei",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedIndex",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedsById",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedsByIdInWei",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedsByIndex",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedsByIndexInWei",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFeedData",
    values: [TestFtsoV2Interface.FeedDataWithProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFeedById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedByIdInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedByIndexInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeedId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeedIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedsById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedsByIdInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedsByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedsByIndexInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFeedData",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TestFtsoV2Interface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestFtsoV2InterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getFeedById(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber] & {
        _value: BigNumber;
        _decimals: number;
        _timestamp: BigNumber;
      }
    >;

    getFeedByIdInWei(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { _value: BigNumber; _timestamp: BigNumber }
    >;

    getFeedByIndex(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber] & {
        _value: BigNumber;
        _decimals: number;
        _timestamp: BigNumber;
      }
    >;

    getFeedByIndexInWei(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { _value: BigNumber; _timestamp: BigNumber }
    >;

    getFeedId(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { _feedId: string }>;

    getFeedIndex(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _index: BigNumber }>;

    getFeedsById(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], number[], BigNumber] & {
        _values: BigNumber[];
        _decimals: number[];
        _timestamp: BigNumber;
      }
    >;

    getFeedsByIdInWei(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber] & { _values: BigNumber[]; _timestamp: BigNumber }
    >;

    getFeedsByIndex(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], number[], BigNumber] & {
        _values: BigNumber[];
        _decimals: number[];
        _timestamp: BigNumber;
      }
    >;

    getFeedsByIndexInWei(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber] & { _values: BigNumber[]; _timestamp: BigNumber }
    >;

    verifyFeedData(
      _feedData: TestFtsoV2Interface.FeedDataWithProofStruct,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getFeedById(
    _feedId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, BigNumber] & {
      _value: BigNumber;
      _decimals: number;
      _timestamp: BigNumber;
    }
  >;

  getFeedByIdInWei(
    _feedId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { _value: BigNumber; _timestamp: BigNumber }
  >;

  getFeedByIndex(
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, BigNumber] & {
      _value: BigNumber;
      _decimals: number;
      _timestamp: BigNumber;
    }
  >;

  getFeedByIndexInWei(
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { _value: BigNumber; _timestamp: BigNumber }
  >;

  getFeedId(
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFeedIndex(
    _feedId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFeedsById(
    _feedIds: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], number[], BigNumber] & {
      _values: BigNumber[];
      _decimals: number[];
      _timestamp: BigNumber;
    }
  >;

  getFeedsByIdInWei(
    _feedIds: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber] & { _values: BigNumber[]; _timestamp: BigNumber }
  >;

  getFeedsByIndex(
    _indices: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], number[], BigNumber] & {
      _values: BigNumber[];
      _decimals: number[];
      _timestamp: BigNumber;
    }
  >;

  getFeedsByIndexInWei(
    _indices: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber] & { _values: BigNumber[]; _timestamp: BigNumber }
  >;

  verifyFeedData(
    _feedData: TestFtsoV2Interface.FeedDataWithProofStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getFeedById(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber] & {
        _value: BigNumber;
        _decimals: number;
        _timestamp: BigNumber;
      }
    >;

    getFeedByIdInWei(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { _value: BigNumber; _timestamp: BigNumber }
    >;

    getFeedByIndex(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber] & {
        _value: BigNumber;
        _decimals: number;
        _timestamp: BigNumber;
      }
    >;

    getFeedByIndexInWei(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { _value: BigNumber; _timestamp: BigNumber }
    >;

    getFeedId(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFeedIndex(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedsById(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], number[], BigNumber] & {
        _values: BigNumber[];
        _decimals: number[];
        _timestamp: BigNumber;
      }
    >;

    getFeedsByIdInWei(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber] & { _values: BigNumber[]; _timestamp: BigNumber }
    >;

    getFeedsByIndex(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], number[], BigNumber] & {
        _values: BigNumber[];
        _decimals: number[];
        _timestamp: BigNumber;
      }
    >;

    getFeedsByIndexInWei(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber] & { _values: BigNumber[]; _timestamp: BigNumber }
    >;

    verifyFeedData(
      _feedData: TestFtsoV2Interface.FeedDataWithProofStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getFeedById(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedByIdInWei(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedByIndex(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedByIndexInWei(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedId(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedIndex(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedsById(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedsByIdInWei(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedsByIndex(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeedsByIndexInWei(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyFeedData(
      _feedData: TestFtsoV2Interface.FeedDataWithProofStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFeedById(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedByIdInWei(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedByIndex(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedByIndexInWei(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedId(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedIndex(
      _feedId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedsById(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedsByIdInWei(
      _feedIds: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedsByIndex(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeedsByIndexInWei(
      _indices: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyFeedData(
      _feedData: TestFtsoV2Interface.FeedDataWithProofStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
