/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFtsoFeedDecimals,
  IFtsoFeedDecimalsInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedDecimals";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes21",
        name: "feedId",
        type: "bytes21",
      },
      {
        indexed: false,
        internalType: "int8",
        name: "decimals",
        type: "int8",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "rewardEpochId",
        type: "uint24",
      },
    ],
    name: "DecimalsChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "decimalsUpdateOffset",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultDecimals",
    outputs: [
      {
        internalType: "int8",
        name: "",
        type: "int8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "_feedId",
        type: "bytes21",
      },
    ],
    name: "getCurrentDecimals",
    outputs: [
      {
        internalType: "int8",
        name: "",
        type: "int8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_feedIds",
        type: "bytes",
      },
    ],
    name: "getCurrentDecimalsBulk",
    outputs: [
      {
        internalType: "bytes",
        name: "_decimals",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "_feedId",
        type: "bytes21",
      },
      {
        internalType: "uint256",
        name: "_rewardEpochId",
        type: "uint256",
      },
    ],
    name: "getDecimals",
    outputs: [
      {
        internalType: "int8",
        name: "",
        type: "int8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_feedIds",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_rewardEpochId",
        type: "uint256",
      },
    ],
    name: "getDecimalsBulk",
    outputs: [
      {
        internalType: "bytes",
        name: "_decimals",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "_feedId",
        type: "bytes21",
      },
    ],
    name: "getScheduledDecimalsChanges",
    outputs: [
      {
        internalType: "int8[]",
        name: "_decimals",
        type: "int8[]",
      },
      {
        internalType: "uint256[]",
        name: "_validFromEpochId",
        type: "uint256[]",
      },
      {
        internalType: "bool[]",
        name: "_fixed",
        type: "bool[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFtsoFeedDecimals__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoFeedDecimalsInterface {
    return new utils.Interface(_abi) as IFtsoFeedDecimalsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFtsoFeedDecimals {
    return new Contract(address, _abi, signerOrProvider) as IFtsoFeedDecimals;
  }
}
