/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IIncreaseManager,
  IIncreaseManagerInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IIncreaseManager";

const _abi = [
  {
    inputs: [],
    name: "getIncentiveDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIncreaseManager__factory {
  static readonly abi = _abi;
  static createInterface(): IIncreaseManagerInterface {
    return new utils.Interface(_abi) as IIncreaseManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIncreaseManager {
    return new Contract(address, _abi, signerOrProvider) as IIncreaseManager;
  }
}
