/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export interface IFtsoGenesisInterface extends utils.Interface {
  functions: {
    "revealPriceSubmitter(address,uint256,uint256,uint256)": FunctionFragment;
    "wNatVotePowerCached(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "revealPriceSubmitter" | "wNatVotePowerCached"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "revealPriceSubmitter",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "wNatVotePowerCached",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "revealPriceSubmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wNatVotePowerCached",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFtsoGenesis extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFtsoGenesisInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    revealPriceSubmitter(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _wNatVP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wNatVotePowerCached(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  revealPriceSubmitter(
    _voter: PromiseOrValue<string>,
    _epochId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    _wNatVP: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wNatVotePowerCached(
    _voter: PromiseOrValue<string>,
    _epochId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    revealPriceSubmitter(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _wNatVP: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    wNatVotePowerCached(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    revealPriceSubmitter(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _wNatVP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wNatVotePowerCached(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    revealPriceSubmitter(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _wNatVP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wNatVotePowerCached(
      _voter: PromiseOrValue<string>,
      _epochId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
